# Matrices


Tabla formada por **m** filas y **n** columnas, conjunto e vectores

$\begin{pmatrix} a_{11} & a_{12} & a_{13} & a_{14} & ... & a_{1n} \\
a_{21} & a_{22} & a_{23} & a_{24} & ... & a_{2n} \\ 
a_{31} & a_{32} & a_{33} & a_{34} & ... & a_{3n} \\ 
a_{41} & a_{42} & a_{43} & a_{44} & ... & a_{4n} \\
... & ... & ... & ... & ... & ... \\
a_{m1} & a_{m2} & a_{m3} & a_{m4} & ... & a_{mn} \\
\end{pmatrix}$

In [11]:
import numpy as np

## Matriz Fila
  $\begin{pmatrix} 1 & 2 & 3 \end{pmatrix}$

In [12]:
np.array([[1,2,3]])

array([[1, 2, 3]])

## Matriz Columna
  $\begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$

In [13]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

## Matriz Nula
Cuando todos sus elementos son nulos

 $\begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{pmatrix}$

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Matriz Cuadrada
Cuando filas y columnas son iguales

ejemplo: cuadrada de orden 4

 $\begin{pmatrix} 1 & 2 & 3 & 3 \\ 7 & 8 & 9 & 1 \\ 12 & 11 & 23 & 9 \\ 2 & 31 & 63 & 19 \end{pmatrix}$

In [16]:
np.array([
    [1, 2, 3, 3],
    [7 ,8 ,9 ,1 ],
    [12 ,11 ,23 ,9 ],
    [ 2, 31, 63, 19]])

array([[ 1,  2,  3,  3],
       [ 7,  8,  9,  1],
       [12, 11, 23,  9],
       [ 2, 31, 63, 19]])

## Matriz Diagonal

Se denomina **Diagonal Principal** a la diagonal de la matriz que va de [A11, A22, ... Amn]

Una matriz diagonal es la que tienen todos sus elementos, a excepcion de la diagonal principal, en nulo

 $\begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 8 & 0 & 0 \\ 0 & 0 & 23 & 0 \\ 0 & 0 & 0 & 19 \end{pmatrix}$

In [17]:
np.array([
    [1, 0, 0, 0],
    [0 ,8 ,0 ,0 ],
    [0 ,0 ,23 ,0 ],
    [ 0, 0, 0, 19]])

array([[ 1,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0, 23,  0],
       [ 0,  0,  0, 19]])