# Indices
- [Matrices](#Matrices)
    - [Matriz Fila](#Matriz-Fila)
    - [Matriz Columna](#Matriz-Columna)
    - [Matriz Nula](#Matriz-Nula)
    - [Matriz Cuadrada](#Matriz-Cuadrada)
    - [Matriz Diagonal](#Matriz-Diagonal)
    - [Matriz Escalar](#Matriz-Escalar)
    - [Matriz Identidad](#Matriz-Identidad)
    - [Matriz triangular superior](#Matriz-triangular-superior)
    - [Matriz triangular inferior](#Matriz->triangular-inferior)

# Matrices


Tabla formada por **m** filas y **n** columnas, conjunto e vectores

$\begin{pmatrix} a_{11} & a_{12} & a_{13} & a_{14} & ... & a_{1n} \\
a_{21} & a_{22} & a_{23} & a_{24} & ... & a_{2n} \\ 
a_{31} & a_{32} & a_{33} & a_{34} & ... & a_{3n} \\ 
a_{41} & a_{42} & a_{43} & a_{44} & ... & a_{4n} \\
... & ... & ... & ... & ... & ... \\
a_{m1} & a_{m2} & a_{m3} & a_{m4} & ... & a_{mn} \\
\end{pmatrix}$

In [9]:
import numpy as np

## Matriz Fila
  $\begin{pmatrix} 1 & 2 & 3 \end{pmatrix}$

In [10]:
np.array([[1,2,3]])

array([[1, 2, 3]])

## Matriz Columna
  $\begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$

In [11]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

## Matriz Nula
Cuando todos sus elementos son nulos

 $\begin{pmatrix} 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \end{pmatrix}$

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matriz Cuadrada
Cuando filas y columnas son iguales

ejemplo: cuadrada de orden 4

 $\begin{pmatrix} 1 & 2 & 3 & 3 \\ 7 & 8 & 9 & 1 \\ 12 & 11 & 23 & 9 \\ 2 & 31 & 63 & 19 \end{pmatrix}$

In [13]:
np.array([
    [1, 2, 3, 3],
    [7 ,8 ,9 ,1 ],
    [12 ,11 ,23 ,9 ],
    [ 2, 31, 63, 19]])

array([[ 1,  2,  3,  3],
       [ 7,  8,  9,  1],
       [12, 11, 23,  9],
       [ 2, 31, 63, 19]])

## Matriz Diagonal

Se denomina **Diagonal Principal** a la diagonal de la matriz que va de [A11, A22, ... Amn]

Una matriz diagonal es la que tienen todos sus elementos, a excepcion de la diagonal principal, en nulo

 $\begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 8 & 0 & 0 \\ 0 & 0 & 23 & 0 \\ 0 & 0 & 0 & 19 \end{pmatrix}$

In [14]:
np.array([
    [1, 0, 0, 0],
    [0 ,8 ,0 ,0 ],
    [0 ,0 ,23 ,0 ],
    [ 0, 0, 0, 19]])

array([[ 1,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0, 23,  0],
       [ 0,  0,  0, 19]])

## Matriz Escalar


Una matriz escapar es una matriz diagonal, con la diagonal principal con los mismos valores

 $\begin{pmatrix} 4 & 0 & 0 & 0 \\ 0 & 4 & 0 & 0 \\ 0 & 0 & 4 & 0 \\ 0 & 0 & 0 & 4 \end{pmatrix}$

In [15]:
np.array([
    [4, 0, 0, 0],
    [0 ,4 ,0 ,0 ],
    [0 ,0 ,4 ,0 ],
    [ 0, 0, 0, 4]])

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

## Matriz Identidad


La matriz identidad, es una matriz escalar con todos los elementos de la diagonal principal en 1

 $\begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix}$

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matriz triangular superior

La Matriz triangular superior tiene todos sus elementos inferiores a la diagonal principal en nulo

 $\begin{pmatrix} 1 & 2 & 2 & 1 \\ 0 & 3 & 5 & 9 \\ 0 & 0 & 4 & 2 \\ 0 & 0 & 0 & 1 \end{pmatrix}$

In [17]:
np.array([
    [1, 2, 2, 1],
    [0 ,3 ,5 ,9 ],
    [0 ,0 ,4 ,2 ],
    [ 0, 0, 0, 1]])

array([[1, 2, 2, 1],
       [0, 3, 5, 9],
       [0, 0, 4, 2],
       [0, 0, 0, 1]])

## Matriz triangular inferior

La Matriz triangular inferior tiene todos sus elementos superiores a la diagonal principal en nulo

 $\begin{pmatrix} 1 & 0 & 0 & 0 \\ 2 & 3 & 0 & 0 \\ 3 & 4 & 4 & 0 \\ 2 & 2 & 4 & 1 \end{pmatrix}$

In [18]:
np.array([
    [1, 0, 0, 0],
    [2 ,3 ,0 ,0 ],
    [3 ,4 ,4 ,0 ],
    [2, 2, 4, 1]])

array([[1, 0, 0, 0],
       [2, 3, 0, 0],
       [3, 4, 4, 0],
       [2, 2, 4, 1]])

# Operaciones con matrices